### ISSUE TITLE
How to get the code area resizable (like a textarea)?

### ISSUE THREAD

**Issue by caub** [satya164/react-simple-code-editor#77]

**Comment by caub** [comment]
By adding resize: 'vertical' in Editor style prop!

closing

**Comment by dsernst** [comment]
Hmm, yes this makes this resizable icon appear in the bottom-right corner, but I still seem unable to click & drag it to resize.

Seeing standard `cursor: text` rather than expected `cursor: se-resize`.

![image](https://user-images.githubusercontent.com/6340841/105923925-112fc600-5ff2-11eb-9de2-f8159d679c6b.png)

On both Chrome & Safari.

**Comment by caub** [comment]
if you want some help, maybe share a repro of your issue (codesandbox, ..)
